name: Validate Bibfile

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/papersite/ruby/Gemfile

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: "mlresearch/papersite"
        ref: "add-dummy-mode"
        path: "papersite"
    - name: Find changed bibfile
      id: changed-files
      uses: tj-actions/changed-files@v20
    - name: Prepare a dummy volume
      run: |
        mkdir v0
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          mv "$file" v0
        done
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: "papersite/ruby"
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Create the volume
      run: |
        cd v0
        bundle exec ../papersite/ruby/create_volume.rb --cicd-mode -v 0 -b *.bib
